/// Tabla auxiliar que agrupa medidas calculadas. [confianza: alta]
table Medidas
	lineageTag: 4e7324a5-5886-43b1-ac02-28cadeb89b39

	/// Porcentaje de cumplimiento (1 + ratio de delta). [confianza: media]
	measure 1_Complete_% = 1 + DIVIDE([1_Target_Delta], [Valor Meta], 0)
		displayFolder: Metas y Targets
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		lineageTag: 0ffac0bb-f7cb-4007-a8c6-a79cc1b32cf8

	/// Porcentaje de cumplimiento (1 + ratio de delta). [confianza: media]
	measure 1_Estado = 1 + DIVIDE([1_Target_Delta], [Valor Meta], 0)
		formatString: "#,##0.00"
		displayFolder: Dinámicas Internas
		lineageTag: 885ca894-3002-47c7-b69b-e5a7fce9a5b5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Espacio1 = 1
		formatString: 0
		lineageTag: 96fc2696-c8d2-44ec-9447-1d0ab409ea7d

	measure Espacio2 = 1
		formatString: 0
		lineageTag: fb92f8f4-2e60-4d91-8218-813054b1a0bc

	measure Espacio3 = 1
		formatString: 0
		lineageTag: f06fd899-759a-4ea0-a080-78a3e44b3b6f

	measure Espacio4 = 1
		formatString: 0
		lineageTag: c95f50f1-1bc9-44cc-8564-ee1040ec2662

	/// Ratio entre [1_Target_Delta] y [Valor Meta], seguro ante divisor cero. [confianza: alta]
	measure 1_Target_% = DIVIDE([1_Target_Delta], [Valor Meta], 0)
		displayFolder: Metas y Targets
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: 451f7c84-2840-4707-9b9b-0792ab5650b8

	/// Diferencia entre [Valor Actual] y [Valor Meta]. [confianza: alta]
	measure 1_Target_Delta = [Valor Actual]-[Valor Meta]
		displayFolder: Comparativos
		formatString: $#,##0,, "MM"
		lineageTag: 28bf91c6-eca9-4e8f-ad9a-0d8029feb5e2

		annotation PBI_FormatHint = {"isCustom":true}

	/// Ratio entre [Valor YoY] y [Valor Interanual], seguro ante divisor cero. [confianza: alta]
	measure 1_YoY_% = DIVIDE([Valor YoY], [Valor Interanual], 0)
		displayFolder: Comparativos
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: 00586bee-5b2b-4428-8549-b868588e505b

		changedProperty = IsHidden

	/// Ratio entre [Valor YTD] y [Valor Cierre Año Anterior], seguro ante divisor cero. [confianza: alta]
	measure 1_YTD_% = DIVIDE([Valor YTD], [Valor Cierre Año Anterior], 0)
		displayFolder: Comparativos
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: 44fa88f1-7b1f-4bec-9808-2cebc5b02601

		changedProperty = IsHidden

	/// Fecha máxima disponible, ignorando filtros de contexto. [confianza: alta]
	measure 'Fecha Actualización' = CALCULATE(MAX('FctProductos'[FEC_CORTE]), ALL('FctProductos'))
		displayFolder: Fechas
		formatString: Short Date
		lineageTag: 3a9185da-8e08-4ebd-bc68-119683bd5394

	/// Fecha máxima disponible, ignorando filtros de contexto. [confianza: alta]
	measure 'Fecha MoM' = EOMONTH(CALCULATE(MAX('FctProductos'[FEC_CORTE]), ALL('FctProductos')), -1)
		displayFolder: Comparativos
		formatString: Short Date
		lineageTag: 2499a566-6f0c-4fdf-b83f-7d1cb6c26692

	/// Fecha máxima disponible, ignorando filtros de contexto. [confianza: alta]
	measure 'Fecha YoY' = EOMONTH(CALCULATE(MAX('FctProductos'[FEC_CORTE]), ALL('FctProductos')), -12)
		displayFolder: Comparativos
		formatString: Short Date
		lineageTag: 89559dfd-6ecc-4a98-afe9-208fefd7aa5d

	/// Fecha máxima disponible, ignorando filtros de contexto. [confianza: alta]
	measure 'Fecha YTD' = DATE(YEAR(CALCULATE(MAX('FctProductos'[FEC_CORTE]), ALL('FctProductos'))) - 1, 12, 31)
		displayFolder: Comparativos
		formatString: Short Date
		lineageTag: 9fdc89d9-075d-4b1e-8648-ed15f01dd4c8

	/// Referencia o multiplicación simple a otra medida. [confianza: alta]
	measure '1_Last_Valor (Eje)' = ```
			[Valor Actual] * 1.01
			
			```
		formatString: "#,##0"
		displayFolder: Conteos
		lineageTag: 64e03c8f-e277-4d4e-85ca-83b7b4e22e2a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Fecha máxima disponible, ignorando filtros de contexto. [confianza: alta]
	measure '1_Last_Valor (%)' = ```
			
			"(" & 
			FORMAT(
			    DIVIDE(
			        [Valor Actual],
			        CALCULATE(
			            [Valor Métrica Seleccionada],
			            FILTER(
			                ALL('FctProductos'),
			                'FctProductos'[FEC_CORTE] = CALCULATE(MAX('FctProductos'[FEC_CORTE]), ALL('FctProductos'))
			            )
			        )
			    ),
			    "0%"
			) 
			& ")"
			```
		formatString: 0.00%
		displayFolder: Conteos
		lineageTag: ccbb8048-5997-4280-be69-a58fc5867696

	/// Fecha máxima disponible, ignorando filtros de contexto. [confianza: alta]
	measure 'Porcentaje Target (Ayer)' = ```
			
			VAR FechaMaxima =
			    CALCULATE(MAX(FctProductos[FEC_CORTE]), ALL(FctProductos))
			
			RETURN
			CALCULATE(
			    SUM(DimMetas[CRECIMIENTO_YTD_%]),
			    FILTER(
			        DimMetas,
			        DimMetas[FEC_CORTE] = FechaMaxima
			    )
			)
			
			```
		formatString: "#,##0.00"
		displayFolder: Metas y Targets
		lineageTag: c057a8df-0786-4deb-bfad-c0f6eb62f32f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// [TODO: validar con negocio] [confianza: baja]
	measure 1_Target_Valor_FinMes = [Valor Cierre Año Anterior]*(1+[Porcentaje Target (Fin Mes Actual)])
		displayFolder: Comparativos
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 283f92cc-0ef7-401a-bdb8-8871fd734d6c

	/// Fecha máxima disponible, ignorando filtros de contexto. [confianza: alta]
	measure 'Porcentaje Target (Fin Mes Actual)' = ```
			
			VAR FechaMaxima =
			    CALCULATE(MAX(FctProductos[FEC_CORTE]), ALL(FctProductos))
			
			VAR FinMes =
			    EOMONTH(FechaMaxima, 0)
			
			RETURN
			CALCULATE(
			    SUM(DimMetas[CRECIMIENTO_YTD_%]),
			    FILTER(
			        DimMetas,
			        DimMetas[FEC_CORTE] = FinMes
			    )
			)
			
			
			```
		formatString: "#,##0.00"
		displayFolder: Metas y Targets
		lineageTag: 1fd7cafd-d983-44a4-91b5-3afdeee0fb09

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Diferencia entre [Valor Actual] y [1_Target_Valor_FinMes]. [confianza: alta]
	measure 1_Target_Delta_FinMes = [Valor Actual]-[1_Target_Valor_FinMes]
		formatString: "\$#,0;(\$#,0);\$#,0"
		displayFolder: Comparativos
		lineageTag: 44815556-09e1-4e5f-a349-0e229edbb9fa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Porcentaje de cumplimiento (1 + ratio de delta). [confianza: media]
	measure 1_Complete_%_FinMes = 1 + DIVIDE([1_Target_Delta_FinMes], [1_Target_Valor_FinMes], 0)
		displayFolder: Metas y Targets
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: 9a5c2568-a1ad-4513-8565-b4ecc9ede4e0

	/// Fecha máxima disponible, ignorando filtros de contexto. [confianza: alta]
	measure 'Etiqueta Meta' = ```
			
			"Meta cierre " & 
			    UPPER(LEFT(FORMAT(CALCULATE(MAX('FctProductos'[FEC_CORTE]), ALL('FctProductos')), "MMMM"), 1)) &
			    MID(FORMAT(CALCULATE(MAX('FctProductos'[FEC_CORTE]), ALL('FctProductos')), "MMMM"), 2, LEN(FORMAT(CALCULATE(MAX('FctProductos'[FEC_CORTE]), ALL('FctProductos')), "MMMM")) - 1)
			
			
			```
		displayFolder: Metas y Targets
		lineageTag: c19023d0-e84e-4a4f-a9ba-5764113af1b8

	/// Fecha máxima disponible, ignorando filtros de contexto. [confianza: alta]
	measure AVG_Saldo_Last = ```
			
			CALCULATE(
			    AVERAGE('FctProductos'[VALOR]), 
			    FILTER(
			        'FctProductos', 
			        'FctProductos'[FEC_CORTE] =  CALCULATE(MAX('FctProductos'[FEC_CORTE]), ALL('FctProductos'))
			         )
			)
			```
		displayFolder: Medidas Primarias
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 9e667b3d-d9e3-4ab7-afc9-f6c5116cb6a1

	/// Fecha máxima disponible, ignorando filtros de contexto. [confianza: alta]
	measure Q_Clientes_Last = ```
			
			CALCULATE(
			    DISTINCTCOUNT(FctProductos[COD_CLIENTE]), 
			    FILTER(
			        'FctProductos', 
			        'FctProductos'[FEC_CORTE] =  CALCULATE(MAX('FctProductos'[FEC_CORTE]), ALL('FctProductos'))
			         )
			)
			```
		displayFolder: Conteos
		formatString: #,0
		lineageTag: adc2bc31-b95f-4117-9380-9aa1cdae0449

	/// Fecha máxima disponible, ignorando filtros de contexto. [confianza: alta]
	measure Q_Cuentas_Last = ```
			
			CALCULATE(
			    DISTINCTCOUNT(FctProductos[COD_PRODUCTO]), 
			    FILTER(
			        'FctProductos', 
			        'FctProductos'[FEC_CORTE] =  CALCULATE(MAX('FctProductos'[FEC_CORTE]), ALL('FctProductos'))
			         )
			)
			```
		displayFolder: Conteos
		formatString: #,0
		lineageTag: 4c475a20-f938-4462-92df-8d124ad92a0f

	/// Fecha máxima disponible, ignorando filtros de contexto. [confianza: alta]
	measure Top25Pct = ```
			
			VAR FechaMaxima =
			    CALCULATE(MAX(FctProductos[FEC_CORTE]), ALL(FctProductos))
			
			VAR Top25Clientes =
			    TOPN(
			        25,
			        SUMMARIZE(
			            FILTER(FctProductos, FctProductos[FEC_CORTE] = FechaMaxima),
			            FctProductos[COD_CLIENTE],
			            "SaldoTotalCliente", SUM(FctProductos[VALOR])
			        ),
			        [SaldoTotalCliente], DESC
			    )
			
			VAR SaldoTop25 =
			    CALCULATE(
			        SUM(FctProductos[VALOR]),
			        FILTER(
			            FctProductos,
			            FctProductos[FEC_CORTE] = FechaMaxima &&
			            FctProductos[COD_CLIENTE] IN SELECTCOLUMNS(Top25Clientes, "COD_CLIENTE", FctProductos[COD_CLIENTE])
			        )
			    )
			
			VAR SaldoTotal =
			    CALCULATE(
			        SUM(FctProductos[VALOR]),
			        FILTER(
			            FctProductos,
			            FctProductos[FEC_CORTE] = FechaMaxima
			        )
			    )
			
			RETURN DIVIDE(SaldoTop25, SaldoTotal, 0)
			
			```
		displayFolder: Indicadores
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 0cef552b-f229-4426-a9fb-fcf2ffa0cad0

	/// Fecha máxima disponible, ignorando filtros de contexto. [confianza: alta]
	measure 1_Last_Valor_SinFormato = ```
			
			CALCULATE(
			    [Valor Métrica Seleccionada], 
			    FILTER(
			        'FctProductos', 
			        'FctProductos'[FEC_CORTE] =  CALCULATE(MAX('FctProductos'[FEC_CORTE]), ALL('FctProductos'))
			         )
			)*1000000
			```
		displayFolder: Conteos
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 0d348908-178a-4af7-b5d7-a1b9a1936cd7

	/// [TODO: validar con negocio] [confianza: baja]
	measure 1_MoM_Delta_SinFormato = ([Valor Actual]-[Valor Mes Anterior])*1000000
		displayFolder: Comparativos
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: b1418b64-3898-4e16-b5de-1faedac83038

	/// [TODO: validar con negocio] [confianza: baja]
	measure 1_YoY_Delta_SinFormato = ([Valor Actual]-[Valor Interanual])*1000000
		displayFolder: Comparativos
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 77ecd204-6e5f-42df-b8de-3f32210fab15

	/// [TODO: validar con negocio] [confianza: baja]
	measure 1_YTD_Delta_SinFormato = ([Valor Actual]-[Valor Cierre Año Anterior])*1000000
		displayFolder: Comparativos
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 4407e633-07ac-4c72-ae0f-854ef82dbe65

	/// [TODO: validar con negocio] [confianza: baja]
	measure TieneDatos = ```
			
			VAR _n =
			    CALCULATE (
			        COUNTROWS ( FctProductos )
			        -- asumiendo relación activa DimTipoProducto[COD_TIPO_PRODUCTO] -> FctProductos[COD_TIPO_PRODUCTO]
			    )
			RETURN IF ( _n > 0, 1, BLANK() )
			
			```
		displayFolder: Indicadores
		formatString: 0
		lineageTag: 4031b85d-e7ba-4d31-aa64-86eb22f5a3b8

	measure Medida
		lineageTag: 06f1c1d6-28d0-4f7f-b39e-2cb343f3de77

		annotation 43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c = True

	/// Promedio ponderado con SUMX. [confianza: media]
	measure 'Tasa Ponderada' = ```
			
			VAR TasaCalc =
			    CALCULATE(
			        DIVIDE(
			            SUMX(
			                FctProductos,
			                FctProductos[TASA] * FctProductos[VALOR]
			            ),
			            SUM(FctProductos[VALOR])
			        ),
			        FILTER(
			            ALL(FctProductos[FEC_CORTE]),
			            FctProductos[FEC_CORTE] =
			                MAXX(ALL(FctProductos[FEC_CORTE]), FctProductos[FEC_CORTE])
			        )
			    )
			RETURN
			    IF(ISBLANK(TasaCalc), 0, TasaCalc)
			
			
			```
		formatString: 0.00
		displayFolder: Indicadores
		lineageTag: f9a2764b-0584-44d6-9eae-3800ee2c6c2b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Medidas
		dataType: string
		lineageTag: 00545ff3-6d6f-481e-9e91-27b95ef4da84
		summarizeBy: none
		sourceColumn: Medidas

		annotation SummarizationSetBy = Automatic

	partition Medidas = m
		mode: import
		queryGroup: Medidas
		source =
				let
				    Origen = ""
				in
				    Origen

	annotation PBI_ResultType = Text

	annotation PBI_NavigationStepName = Navegación

